### ISSUE TITLE
.r-Defaults *:not(body) selector needs longer selector than `.className` to be overriden

### ISSUE THREAD

**Issue by bloodyowl** [cssrecipes/defaults#5]
as this is _defaults_ I expect not having to use `.r-Defaults .mySelector` to override the default background settings. 

what do you think?

**Comment by MoOx** [comment]
Yeah I'm getting this issue for other lib (like vertical-rhythm).
Prefixing all the things is a bit brutal.

ugly workaround (without using r-*): `.mySelector.mySelector`

The problem is if this lib is used by a component (not on html).
Solutions:
- remove class & warn it's for html only
- keep prefix & get issues all the times

**Comment by MoOx** [comment]
At the same time, what do you think to include normalize directly?

**Comment by bloodyowl** [comment]
what do you mean by that?

**Comment by MoOx** [comment]
according to irc discussion we will remove the class & warn it's for HTML only. And no normalize

**Comment by MoOx** [comment]
Also, I've exploded content in lib/\* (nice if people don't want all defaults). index.css is still importing everything.

**Comment by bloodyowl** [comment]
:+1:

**Comment by magsout** [comment]
Nice :+1:
